/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <android/log.h>
#include <unistd.h>
#include <pthread.h>
#include <sys/wait.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/types.h>
#include "utils.h"
#include "listen_file.h"

/* Header for class com_jason_uninstall_Uninstall */

#ifndef _Included_com_jason_uninstall_Uninstall
#define _Included_com_jason_uninstall_Uninstall
#ifdef __cplusplus
extern "C" {
#endif

#define loge(...) __android_log_print(ANDROID_LOG_ERROR,"HJT",__VA_ARGS__)
#define PORT 38888
#define MAX_BUF 1024
#define NO_CHECK_PIPE -1

/*
 * Class:     com_jason_uninstall_Uninstall
 * Method:    listenerUninstall
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jason_uninstall_Uninstall_listenerUninstall(
		JNIEnv *, jclass, jstring,jstring, jstring);

/*
 * Class:     com_jason_uninstall_Uninstall
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jason_uninstall_Uninstall_stop
(JNIEnv *, jclass,jstring);

void start_server(int,const char*);

int start_client(int);

int check_server_port();

void *interaction_command(void *i);
void *interaction_file(void*);
void *interaction_port_file(void *buf);

#ifdef __cplusplus
}
#endif
#endif

